baseurl = "/"
languageCode = "en-us"
title = "Qi Li"
theme = "ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/cn/about/"
    weight = 2
[[menu.main]]
    name = "博文"
    url = "/cn/"
    weight = 3
[[menu.main]]
    name = "English"
    url = "/en/"
    weight = 5
[[menu.main]]
    name = "杂七杂八"
    url = "/xx/"
    weight = 4

    
[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.cn]]
    name = "博文"
    url  = "/cn/"
    weight = 2
[[menu.cn]]
    name = "简历"
    url  = "/cn/cv/"
    weight = 3
[[menu.cn]]
    name = "English"
    url  = "/en/"
    weight = 4
    
    
[params]
    description = "Statistics, Models, and Life"
    footer = "&copy; [Qi Li](https://qili.site) 2018 | [Github](https://github.com/itsjustqi) | [Twitter](https://twitter.com/itsjustqi)"

   highlightjsVersion = "9.12.0"
   highlightjsCDN = "//cdn.bootcss.com"
   highlightjsLang = ["r", "yaml", "tex"]
   highlightjsTheme = "github"
   
[frontmatter]
  date: ['date', ':filename', ':default']